<a href="https://colab.research.google.com/github/shubhangi942/workshop/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #What is alias?

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

#Output -> [1,2,3]

[1 2 3]


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
#Output ->
 [[1 2 3]
 [4 5 6]]

IndentationError: unexpected indent (<ipython-input-10-3aead49e0a66>, line 4)

In [11]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# dtype
np.array([1,2,3],dtype=float)
# Output -> array([1., 2., 3.])

a = np.array([1, 2, 3], dtype=np.uint8)
print(a)
print(a.dtype)
# Output array([1 2 3]), uint8

b = np.array([1, 2, 3], dtype=complex)
print(b)
print(b.dtype)



[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [14]:
import numpy as np
a = np.arange(0, 10, 2)
print(a)


[0 2 4 6 8]


In [15]:
#Example1
import numpy as np
a = np.arange(12)  # Creates a 1D array from 0 to 11
b = a.reshape(3, 4)  # Reshape it into a 3x4 2D array
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
#2
import numpy as np
a = np.arange(24)  # Creates a 1D array from 0 to 23
b = a.reshape(2, 3, 4)  # Reshape it into a 2x3x4 3D array
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [17]:
# np.ones and np.zeros
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
b = np.zeros((3, 3), dtype=int)  # 3x3 array of zeros, integer type
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
# first example
import numpy as np
a = np.random.random()
print(a)


# second example of shape
a = np.random.random((2, 3))
print(a)



0.6890646482589826
[[0.64146039 0.37200037 0.36528987]
 [0.05879314 0.17308649 0.8520735 ]]


In [20]:
import numpy as np
a = np.identity(3)
print(a)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
a1 = np.arange(10, dtype=np.int32)
print("Before:", a1)

Before: [0 1 2 3 4 5 6 7 8 9]


In [22]:
a1 = np.array([3,4,2,5,7])

In [24]:
a1.size

5

In [23]:
a1.shape

(5,)

In [25]:
a1.dtype

dtype('int64')

In [26]:
a1.itemsize

8

In [28]:
a1.nbytes

40

In [29]:
a2 = np.array([[2,3],[75,7]])

In [33]:
a3.dtype

NameError: name 'a3' is not defined

In [34]:
a3 = np.array([3,4,2,5,7])

In [35]:
a3.size

5

In [36]:
a3.shape

(5,)

In [37]:
a3.dtype

dtype('int64')

In [38]:
a3.itemsize

8

In [39]:
# astype
a3.astype(np.int32)
a1.astype (np.float32).dtype

dtype('float32')

In [43]:
# max/min/sum/prod
# 0 -> coi and 1 -> row
a1=np.array([[1,2],[3,4]])
a1
np,sum(a1,axis=0)

TypeError: 'axis' is an invalid keyword argument for sum()

In [44]:
<html>
  <head>
    <title>Sample Page</title>
  </head>
  <body>
    <h1>Product List</h1>
    <p>Email: john.doe@example.com</p>
    <p>Phone: +91-9876543210</p>
    <p>Date: 20-Apr-2025</p>
    <p>Price: ₹499.99</p>

    <p>Email: jane123@test.in</p>
    <p>Phone: 022-23456789</p>
    <p>Date: 15-Mar-2024</p>
    <p>Price: ₹1299</p>

    <a href="https://example.com">Visit Example</a>
    <a href="https://shop.com/product/123">Buy Now</a>
  </body>
</html>

SyntaxError: invalid character '₹' (U+20B9) (<ipython-input-44-2d1103d76c77>, line 10)